# fMRI Longitudinal Pipeline: Long to Wide + Merge

This notebook creates a reproducible pipeline to:
- Convert motion metrics long -> wide (`T1`, `T2`, and variable suffixes `_T1`/`_T2`).
- Convert contrasts long -> wide using ROI-based columns (`ROI_metric_T1`/`ROI_metric_T2`).
- Match (merge) motion and contrasts into one final participant-level table.
- Export all outputs to one Excel workbook.

In [24]:
import re
from pathlib import Path

import pandas as pd

pd.set_option("display.max_columns", 300)

# Inputs
MOTION_FILE = Path(r"C:\Users\okkam\Desktop\labo\article 2\Longitudinal_Multimodal_Data_CIMAQ\fMRI\ALL_MOTION_METRICS.xlsx")
CONTRASTS_FILE = Path(r"C:\Users\okkam\Desktop\labo\article 2\Longitudinal_Multimodal_Data_CIMAQ\fMRI\119_contrasts.xlsx")

# Output
OUT_FILE = MOTION_FILE.parent / "long_to_wide_fMRI_outputs.xlsx"

MOTION_FILE, CONTRASTS_FILE, OUT_FILE

(WindowsPath('C:/Users/okkam/Desktop/labo/article 2/Longitudinal_Multimodal_Data_CIMAQ/fMRI/ALL_MOTION_METRICS.xlsx'),
 WindowsPath('C:/Users/okkam/Desktop/labo/article 2/Longitudinal_Multimodal_Data_CIMAQ/fMRI/119_contrasts.xlsx'),
 WindowsPath('C:/Users/okkam/Desktop/labo/article 2/Longitudinal_Multimodal_Data_CIMAQ/fMRI/long_to_wide_fMRI_outputs.xlsx'))

In [25]:
def _auto_find_id_session_columns(df: pd.DataFrame):
    cols = list(df.columns)
    lower_map = {c.lower().strip(): c for c in cols}

    id_candidates = [
        lower_map.get("id"),
        lower_map.get("participant_id"),
        lower_map.get("subject"),
        cols[0] if len(cols) > 0 else None,
    ]
    ses_candidates = [
        lower_map.get("session"),
        lower_map.get("visit"),
        cols[1] if len(cols) > 1 else None,
    ]

    id_col = next((c for c in id_candidates if c in df.columns), None)
    session_col = next((c for c in ses_candidates if c in df.columns), None)

    if id_col is None or session_col is None:
        raise ValueError("Could not identify ID and Session columns.")

    return id_col, session_col


def _session_numeric_order(series: pd.Series) -> pd.Series:
    extracted = series.astype(str).str.extract(r"(\d+)", expand=False)
    return pd.to_numeric(extracted, errors="coerce").fillna(9999)


def _clean_label(value: str) -> str:
    x = str(value).strip()
    x = re.sub(r"\s+", "_", x)
    x = re.sub(r"[^A-Za-z0-9_.-]", "", x)
    return x


def long_to_wide_two_timepoints(df: pd.DataFrame, id_col: str, session_col: str, variable_columns=None) -> pd.DataFrame:
    x = df.copy()
    if variable_columns is None:
        variable_columns = [c for c in x.columns if c not in [id_col, session_col]]

    x = x.dropna(subset=[id_col, session_col]).copy()
    x["_session_num"] = _session_numeric_order(x[session_col])
    x = x.sort_values([id_col, "_session_num", session_col])
    x["_tp"] = x.groupby(id_col).cumcount() + 1
    x = x[x["_tp"].isin([1, 2])].copy()

    session_wide = (
        x.pivot_table(index=id_col, columns="_tp", values=session_col, aggfunc="first")
        .rename(columns={1: "T1", 2: "T2"})
    )

    parts = [session_wide]
    for var in variable_columns:
        p = x.pivot_table(index=id_col, columns="_tp", values=var, aggfunc="first")
        p = p.rename(columns={1: f"{var}_T1", 2: f"{var}_T2"})
        parts.append(p)

    out = pd.concat(parts, axis=1).reset_index()

    t1_vars = [f"{v}_T1" for v in variable_columns if f"{v}_T1" in out.columns]
    t2_vars = [f"{v}_T2" for v in variable_columns if f"{v}_T2" in out.columns]
    final_cols = [id_col, "T1"] + t1_vars + ["T2"] + t2_vars
    final_cols = [c for c in final_cols if c in out.columns]
    return out[final_cols]


def classify_roi_name(roi_name: str) -> str:
    v = str(roi_name).strip().lower()
    if "hippocampus" in v:
        return "01_hippocampus"
    if "parietal_sup" in v or "superior_pariet" in v:
        return "02_superior_parietal_cortex"
    if any(k in v for k in ["parahipp", "entorh", "subiculum", "fornix", "fimbria", "hippocampal"]):
        return "03_hippocampus_related"
    if "precuneus" in v:
        return "04_precuneus"
    if any(k in v for k in ["cingulum_ant", "acc", "anterior_cing"]):
        return "05_acc"
    return "99_rest"


def long_to_wide_contrasts_by_roi(df: pd.DataFrame) -> pd.DataFrame:
    x = df.copy()
    x.columns = [c.strip() for c in x.columns]

    id_col, session_col = _auto_find_id_session_columns(x)
    roi_col = [c for c in x.columns if "roi" in c.lower()][0]
    x[roi_col] = x[roi_col].astype(str).str.strip()

    metric_cols = [c for c in x.columns if c not in [id_col, session_col, roi_col]]

    ses_map = x[[id_col, session_col]].drop_duplicates().copy()
    ses_map["_session_num"] = _session_numeric_order(ses_map[session_col])
    ses_map = ses_map.sort_values([id_col, "_session_num", session_col])
    ses_map["_tp"] = ses_map.groupby(id_col).cumcount() + 1
    ses_map = ses_map[ses_map["_tp"].isin([1, 2])]

    x = x.merge(ses_map[[id_col, session_col, "_tp"]], on=[id_col, session_col], how="inner")

    session_wide = (
        ses_map.pivot_table(index=id_col, columns="_tp", values=session_col, aggfunc="first")
        .rename(columns={1: "T1", 2: "T2"})
    )

    parts = [session_wide]
    for metric in metric_cols:
        p = x.pivot_table(index=id_col, columns=["_tp", roi_col], values=metric, aggfunc="first")
        p.columns = [
            f"{_clean_label(roi)}_{_clean_label(metric)}_T{int(tp)}"
            for tp, roi in p.columns
        ]
        parts.append(p)

    out = pd.concat(parts, axis=1).reset_index()

    t1_cols = [c for c in out.columns if str(c).endswith("_T1")]
    t2_cols = [c for c in out.columns if str(c).endswith("_T2")]

    def _sort_key(col_name: str):
        base = col_name.rsplit("_T", 1)[0]
        parts = base.split("_")
        metric = parts[-1] if parts else ""
        roi = "_".join(parts[:-1]) if len(parts) > 1 else base
        return (classify_roi_name(roi), roi.lower(), metric.lower())

    t1_cols = sorted(t1_cols, key=_sort_key)
    t2_cols = sorted(t2_cols, key=_sort_key)

    final_cols = [id_col, "T1"] + t1_cols + ["T2"] + t2_cols
    final_cols = [c for c in final_cols if c in out.columns]
    return out[final_cols]


print("Helpers loaded.")

Helpers loaded.

In [26]:
# 1) Motion: long -> wide
motion_long = pd.read_excel(MOTION_FILE)
id_col_m, ses_col_m = _auto_find_id_session_columns(motion_long)
motion_vars = [c for c in motion_long.columns if c not in [id_col_m, ses_col_m]]

motion_wide = long_to_wide_two_timepoints(
    motion_long,
    id_col=id_col_m,
    session_col=ses_col_m,
    variable_columns=motion_vars,
)

print("Motion long:", motion_long.shape)
print("Motion wide:", motion_wide.shape)
motion_wide.head()

Motion long: (139, 15)
Motion wide: (74, 29)

_tp,ID,T1,TD_mean_T1,TD_STD_T1,TD_median_T1,TD_max_T1,TD_>1mm_T1,TD_>2mm_T1,TD_>3mm_T1,STS_mean_T1,STS_STD_T1,STS_median_T1,STS_max_T1,STS_>0.5mm_T1,STS_>1mm_T1,T2,TD_mean_T2,TD_STD_T2,TD_median_T2,TD_max_T2,TD_>1mm_T2,TD_>2mm_T2,TD_>3mm_T2,STS_mean_T2,STS_STD_T2,STS_median_T2,STS_max_T2,STS_>0.5mm_T2,STS_>1mm_T2
0,3002498,t04,0.4579,0.1482,0.4989,0.7831,0.0,0.0,0.0,0.1565,0.1132,0.1324,1.1124,4.0,1.0,t06,0.2214,0.0826,0.2172,0.4921,0.0,0.0,0.0,0.1950,0.1154,0.1727,1.2546,6.0,1.0
1,3025432,t02,0.8227,0.3557,0.9174,1.4089,284.0,0.0,0.0,0.2220,0.2880,0.1585,2.8437,29.0,15.0,t06,0.8135,0.2308,0.8608,1.5575,112.0,0.0,0.0,0.1848,0.2564,0.1360,2.9957,17.0,11.0
2,3100205,t04,0.9387,0.2679,1.0113,1.3353,320.0,0.0,0.0,0.2841,0.1428,0.2588,2.6461,23.0,1.0,t08,0.6674,0.1899,0.6966,1.1379,16.0,0.0,0.0,0.3701,0.1898,0.3464,2.6835,127.0,6.0
3,3123186,t02,0.5541,0.2232,0.6061,1.0273,6.0,0.0,0.0,0.1965,0.1636,0.1386,1.6715,37.0,1.0,t04,0.1691,0.0976,0.1458,0.5049,0.0,0.0,0.0,0.2641,0.2057,0.1803,1.0529,54.0,1.0
4,3149469,t04,0.3443,0.1434,0.3848,0.6536,0.0,0.0,0.0,0.1342,0.0493,0.1312,0.3103,0.0,0.0,t06,0.4423,0.2374,0.4952,0.9153,0.0,0.0,0.0,0.1949,0.0819,0.1873,0.7871,4.0,0.0

In [27]:
# 2) Contrasts: long -> wide (ROI-based)
contrasts_long = pd.read_excel(CONTRASTS_FILE)
contrasts_wide = long_to_wide_contrasts_by_roi(contrasts_long)

x_tmp = contrasts_long.copy()
x_tmp.columns = [c.strip() for c in x_tmp.columns]
roi_col_tmp = [c for c in x_tmp.columns if "roi" in c.lower()][0]
group_counts = (
    x_tmp[roi_col_tmp]
    .astype(str)
    .str.strip()
    .map(classify_roi_name)
    .value_counts()
    .sort_index()
)

print("Contrasts long:", contrasts_long.shape)
print("Contrasts wide:", contrasts_wide.shape)
print("\nROI counts by custom group:")
print(group_counts)
contrasts_wide.head()

Contrasts long: (9684, 7)
Contrasts wide: (71, 659)

ROI counts by custom group:
ROI name
01_hippocampus                  238
02_superior_parietal_cortex     230
03_hippocampus_related          236
04_precuneus                    238
05_acc                          237
99_rest                        8505
Name: count, dtype: int64

,ID,T1,Hippocampus_L_Average_T1,Hippocampus_L_Size_T1,Hippocampus_L_Std.Dev._T1,Hippocampus_L_T_T1,Hippocampus_R_Average_T1,Hippocampus_R_Size_T1,Hippocampus_R_Std.Dev._T1,Hippocampus_R_T_T1,Parietal_Sup_L_Average_T1,Parietal_Sup_L_Size_T1,Parietal_Sup_L_Std.Dev._T1,Parietal_Sup_L_T_T1,Parietal_Sup_R_Average_T1,Parietal_Sup_R_Size_T1,Parietal_Sup_R_Std.Dev._T1,Parietal_Sup_R_T_T1,ParaHippocampal_L_Average_T1,ParaHippocampal_L_Size_T1,ParaHippocampal_L_Std.Dev._T1,ParaHippocampal_L_T_T1,ParaHippocampal_R_Average_T1,ParaHippocampal_R_Size_T1,ParaHippocampal_R_Std.Dev._T1,ParaHippocampal_R_T_T1,Precuneus_L_Average_T1,Precuneus_L_Size_T1,Precuneus_L_Std.Dev._T1,Precuneus_L_T_T1,Precuneus_R_Average_T1,Precuneus_R_Size_T1,Precuneus_R_Std.Dev._T1,Precuneus_R_T_T1,Cingulum_Ant_L_Average_T1,Cingulum_Ant_L_Size_T1,Cingulum_Ant_L_Std.Dev._T1,Cingulum_Ant_L_T_T1,Cingulum_Ant_R_Average_T1,Cingulum_Ant_R_Size_T1,Cingulum_Ant_R_Std.Dev._T1,Cingulum_Ant_R_T_T1,Amygdala_L_Average_T1,Amygdala_L_Size_T1,Amygdala_L_Std.Dev._T1,Amygdala_L_T_T1,Amygdala_R_Average_T1,Amygdala_R_Size_T1,Amygdala_R_Std.Dev._T1,Amygdala_R_T_T1,Angular_L_Average_T1,Angular_L_Size_T1,Angular_L_Std.Dev._T1,Angular_L_T_T1,Angular_R_Average_T1,Angular_R_Size_T1,Angular_R_Std.Dev._T1,Angular_R_T_T1,Calcarine_L_Average_T1,Calcarine_L_Size_T1,Calcarine_L_Std.Dev._T1,Calcarine_L_T_T1,Calcarine_R_Average_T1,Calcarine_R_Size_T1,Calcarine_R_Std.Dev._T1,Calcarine_R_T_T1,Cingulum_Mid_L_Average_T1,Cingulum_Mid_L_Size_T1,Cingulum_Mid_L_Std.Dev._T1,Cingulum_Mid_L_T_T1,Cingulum_Mid_R_Average_T1,Cingulum_Mid_R_Size_T1,Cingulum_Mid_R_Std.Dev._T1,Cingulum_Mid_R_T_T1,Cingulum_Post_L_Average_T1,Cingulum_Post_L_Size_T1,Cingulum_Post_L_Std.Dev._T1,Cingulum_Post_L_T_T1,Cingulum_Post_R_Average_T1,Cingulum_Post_R_Size_T1,Cingulum_Post_R_Std.Dev._T1,Cingulum_Post_R_T_T1,Cuneus_L_Average_T1,Cuneus_L_Size_T1,Cuneus_L_Std.Dev._T1,Cuneus_L_T_T1,Cuneus_R_Average_T1,Cuneus_R_Size_T1,Cuneus_R_Std.Dev._T1,Cuneus_R_T_T1,Frontal_Inf_Oper_L_Average_T1,Frontal_Inf_Oper_L_Size_T1,Frontal_Inf_Oper_L_Std.Dev._T1,Frontal_Inf_Oper_L_T_T1,Frontal_Inf_Oper_R_Average_T1,Frontal_Inf_Oper_R_Size_T1,Frontal_Inf_Oper_R_Std.Dev._T1,Frontal_Inf_Oper_R_T_T1,Frontal_Inf_Orb_L_Average_T1,Frontal_Inf_Orb_L_Size_T1,Frontal_Inf_Orb_L_Std.Dev._T1,Frontal_Inf_Orb_L_T_T1,Frontal_Inf_Orb_R_Average_T1,Frontal_Inf_Orb_R_Size_T1,Frontal_Inf_Orb_R_Std.Dev._T1,Frontal_Inf_Orb_R_T_T1,Frontal_Inf_Tri_L_Average_T1,Frontal_Inf_Tri_L_Size_T1,Frontal_Inf_Tri_L_Std.Dev._T1,Frontal_Inf_Tri_L_T_T1,Frontal_Inf_Tri_R_Average_T1,Frontal_Inf_Tri_R_Size_T1,Frontal_Inf_Tri_R_Std.Dev._T1,Frontal_Inf_Tri_R_T_T1,Frontal_Med_Orb_L_Average_T1,Frontal_Med_Orb_L_Size_T1,Frontal_Med_Orb_L_Std.Dev._T1,Frontal_Med_Orb_L_T_T1,Frontal_Med_Orb_R_Average_T1,Frontal_Med_Orb_R_Size_T1,Frontal_Med_Orb_R_Std.Dev._T1,Frontal_Med_Orb_R_T_T1,Frontal_Mid_L_Average_T1,Frontal_Mid_L_Size_T1,Frontal_Mid_L_Std.Dev._T1,Frontal_Mid_L_T_T1,Frontal_Mid_Orb_L_Average_T1,Frontal_Mid_Orb_L_Size_T1,Frontal_Mid_Orb_L_Std.Dev._T1,Frontal_Mid_Orb_L_T_T1,Frontal_Mid_Orb_R_Average_T1,Frontal_Mid_Orb_R_Size_T1,Frontal_Mid_Orb_R_Std.Dev._T1,Frontal_Mid_Orb_R_T_T1,Frontal_Mid_R_Average_T1,Frontal_Mid_R_Size_T1,Frontal_Mid_R_Std.Dev._T1,Frontal_Mid_R_T_T1,Frontal_Sup_L_Average_T1,Frontal_Sup_L_Size_T1,Frontal_Sup_L_Std.Dev._T1,Frontal_Sup_L_T_T1,Frontal_Sup_Medial_L_Average_T1,Frontal_Sup_Medial_L_Size_T1,Frontal_Sup_Medial_L_Std.Dev._T1,Frontal_Sup_Medial_L_T_T1,Frontal_Sup_Medial_R_Average_T1,Frontal_Sup_Medial_R_Size_T1,Frontal_Sup_Medial_R_Std.Dev._T1,Frontal_Sup_Medial_R_T_T1,...,Insula_L_Std.Dev._T2,Insula_L_T_T2,Insula_R_Average_T2,Insula_R_Size_T2,Insula_R_Std.Dev._T2,Insula_R_T_T2,Lingual_L_Average_T2,Lingual_L_Size_T2,Lingual_L_Std.Dev._T2,Lingual_L_T_T2,Lingual_R_Average_T2,Lingual_R_Size_T2,Lingual_R_Std.Dev._T2,Lingual_R_T_T2,Occipital_Inf_L_Average_T2,Occipital_Inf_L_Size_T2,Occipital_Inf_L_Std.Dev._T2,Occipital_Inf_L_T_T2,Occipital_Inf_R_Average_T2,Occipital_Inf_R_Size_T2,Occipital_Inf_R_Std.Dev._T2,Occipital_Inf_R_T_T2,Occipital_Mid_L_Average_T2,Occipital_Mid_L_Size_T2,Occipital_Mid_L_Std.Dev._T2,Occipital_Mid_L_T_T2,Occipital_Mid_R_Average_T2,Occipital_Mid_R_Size_T2,Occipital_Mid_R_Std.Dev._T2,Occipital_Mid_R_T_T2,Occipital_Sup_L_Average_T2,Occipital_Sup_L_Size_T2,Occipital_Sup_L_Std.Dev._T2,Occipital_Sup_L_T_T2,Occipital_Sup_R_Average_T2,Occipital_Sup_R_Size_T2,Occipital_Sup_R_Std.Dev._T2,Occipital_Sup_R_T_T2,Olfactory_L_Average_T2,Olfactory_L_Size_T2,Olfactory_L_Std.Dev._T2,Olfactory_L_T_T2,Olfactory_R_Average_T2,Olfactory_R_Size_T2,Olfactory_R_Std.Dev._T2,Olfactory_R_T_T2,Paracentral_Lobule_L_Average_T2,Paracentral_Lobule_L_Size_T2,Paracentral_Lobule_L_Std.Dev._T2,Paracentral_Lobule_L_T_T2,Paracentral_Lobule_R_Average_T2,Paracentral_Lobule_R_Size_T2,Paracentral_Lobule_R_Std.Dev._T2,Paracentral_Lobule_R_T_T2,Parietal_Inf_L_Average_T2,Parietal_Inf_L_Size_T2,Parietal_Inf_L_Std.Dev._T2,Parietal_Inf_L_T_T2,Parietal_Inf_R_Average_T2,Parietal_Inf_R_Size_T2,Parietal_Inf_R_Std.Dev._T2,Parietal_Inf_R_T_T2,Postcentral_L_Average_T2,Postcentral_L_Size_T2,Postcentral_L_Std.Dev._T2,Postcentral_L_T_T2,Postcentral_R_Average_T2,Postcentral_R_Size_T2,Postcentral_R_Std.Dev._T2,Postcentral_R_T_T2,Precentral_L_Average_T2,Precentral_L_Size_T2,Precentral_L_Std.Dev._T2,Precentral_L_T_T2,Precentral_R_Average_T2,Precentral_R_Size_T2,Precentral_R_Std.Dev._T2,Precentral_R_T_T2,Rectus_L_Average_T2,Rectus_L_Size_T2,Rectus_L_Std.Dev._T2,Rectus_L_T_T2,Rectus_R_Average_T2,Rectus_R_Size_T2,Rectus_R_Std.Dev._T2,Rectus_R_T_T2,Rolandic_Oper_L_Average_T2,Rolandic_Oper_L_Size_T2,Rolandic_Oper_L_Std.Dev._T2,Rolandic_Oper_L_T_T2,Rolandic_Oper_R_Average_T2,Rolandic_Oper_R_Size_T2,Rolandic_Oper_R_Std.Dev._T2,Rolandic_Oper_R_T_T2,Supp_Motor_Area_L_Average_T2,Supp_Motor_Area_L_Size_T2,Supp_Motor_Area_L_Std.Dev._T2,Supp_Motor_Area_L_T_T2,Supp_Motor_Area_R_Average_T2,Supp_Motor_Area_R_Size_T2,Supp_Motor_Area_R_Std.Dev._T2,Supp_Motor_Area_R_T_T2,SupraMarginal_L_Average_T2,SupraMarginal_L_Size_T2,SupraMarginal_L_Std.Dev._T2,SupraMarginal_L_T_T2,SupraMarginal_R_Average_T2,SupraMarginal_R_Size_T2,SupraMarginal_R_Std.Dev._T2,SupraMarginal_R_T_T2,Temporal_Inf_L_Average_T2,Temporal_Inf_L_Size_T2,Temporal_Inf_L_Std.Dev._T2,Temporal_Inf_L_T_T2,Temporal_Inf_R_Average_T2,Temporal_Inf_R_Size_T2,Temporal_Inf_R_Std.Dev._T2,Temporal_Inf_R_T_T2,Temporal_Mid_L_Average_T2,Temporal_Mid_L_Size_T2,Temporal_Mid_L_Std.Dev._T2,Temporal_Mid_L_T_T2,Temporal_Mid_R_Average_T2,Temporal_Mid_R_Size_T2,Temporal_Mid_R_Std.Dev._T2,Temporal_Mid_R_T_T2,Temporal_Pole_Mid_L_Average_T2,Temporal_Pole_Mid_L_Size_T2,Temporal_Pole_Mid_L_Std.Dev._T2,Temporal_Pole_Mid_L_T_T2,Temporal_Pole_Mid_R_Average_T2,Temporal_Pole_Mid_R_Size_T2,Temporal_Pole_Mid_R_Std.Dev._T2,Temporal_Pole_Mid_R_T_T2,Temporal_Pole_Sup_L_Average_T2,Temporal_Pole_Sup_L_Size_T2,Temporal_Pole_Sup_L_Std.Dev._T2,Temporal_Pole_Sup_L_T_T2,Temporal_Pole_Sup_R_Average_T2,Temporal_Pole_Sup_R_Size_T2,Temporal_Pole_Sup_R_Std.Dev._T2,Temporal_Pole_Sup_R_T_T2,Temporal_Sup_L_Average_T2,Temporal_Sup_L_Size_T2,Temporal_Sup_L_Std.Dev._T2,Temporal_Sup_L_T_T2,Temporal_Sup_R_Average_T2,Temporal_Sup_R_Size_T2,Temporal_Sup_R_Std.Dev._T2,Temporal_Sup_R_T_T2
0,3002498,t04,0.204866,932.0,0.187010,1.09548,0.141722,946.0,0.193112,0.733888,-0.050055,1780.0,0.240597,-0.208046,-0.366434,1643.0,0.337222,-1.08663,0.035731,823.0,0.184553,0.193611,0.014009,957.0,0.165820,0.084486,-0.097804,3425.0,0.258852,-0.377836,-0.249717,3089.0,0.311789,-0.800918,-0.064639,1394.0,0.299906,-0.21553,-0.086699,1311.0,0.240799,-0.36005,-0.095064,220.0,0.260898,-0.364373,-0.060107,248.0,0.098262,-0.611702,-0.365052,1081.0,0.298737,-1.22199,-0.487776,1471.0,0.447072,-1.09105,0.259278,2195.0,0.359261,0.721698,0.170228,1857.0,0.400255,0.425298,0.160467,1935.0,0.210446,0.762511,0.102210,2203.0,0.193602,0.527941,0.210002,463.0,0.244451,0.859076,-0.010481,335.0,0.167743,-0.062482,0.085524,1451.0,0.356379,0.239981,-0.049829,1414.0,0.296499,-0.168059,0.117714,911.0,0.212472,0.554023,0.049217,1252.0,0.332238,0.148139,-0.197369,1515.0,0.293561,-0.672327,-0.307062,1398.0,0.258120,-1.18961,-0.093633,2142.0,0.341122,-0.274484,-0.085812,1717.0,0.253189,-0.338926,0.012690,698.0,0.219897,0.057711,-0.331844,847.0,0.287823,-1.15295,0.107346,4076.0,0.320551,0.33488,-0.394270,822.0,0.264750,-1.48922,-0.515289,945.0,0.301520,-1.70897,-0.047219,4555.0,0.328835,-0.143595,0.085903,3283.0,0.351551,0.244355,-0.137673,2876.0,0.252577,-0.545075,-0.203212,2106.0,0.291412,-0.697337,...,0.542574,0.378826,-0.050817,1770.0,0.653383,-0.077775,0.234619,2089.0,0.475664,0.493245,0.240846,2278.0,0.619264,0.388924,1.013770,906.0,0.423499,2.3938,1.144590,868.0,0.410760,2.78652,0.643511,3024.0,0.451096,1.42655,0.692905,1750.0,0.413835,1.67435,0.725632,1262.0,0.408545,1.77614,0.388638,1285.0,0.282067,1.37782,0.453129,192.0,0.352038,1.28716,0.157663,199.0,0.173972,0.906255,0.337478,1297.0,0.258753,1.30425,0.377556,779.0,0.347475,1.08657,0.989604,2343.0,0.380336,2.60192,0.079665,1166.0,0.484766,0.164336,0.612459,3467.0,0.369901,1.65574,0.684637,3273.0,0.373265,1.83418,0.661695,3129.0,0.278573,2.3753,0.692507,3016.0,0.310242,2.23215,0.423050,622.0,0.316394,1.3371,0.301388,568.0,0.245449,1.22791,-0.148442,947.0,0.210814,-0.704137,-0.071791,1246.0,0.367237,-0.19549,0.679373,2124.0,0.305418,2.22441,0.568340,2367.0,0.324584,1.75098,0.542410,1173.0,0.458321,1.18347,0.396334,1715.0,0.430618,0.920384,0.412739,2391.0,0.404667,1.01995,0.309216,2997.0,0.376993,0.820215,-0.037256,4197.0,0.436231,-0.085405,-0.129824,3792.0,0.556996,-0.233078,0.121128,459.0,0.326445,0.371052,0.366434,634.0,0.323095,1.13414,0.573804,985.0,0.758305,0.756692,0.775702,900.0,0.781886,0.99209,-0.244715,2174.0,0.658876,-0.371413,-0.198090,2813.0,0.551978,-0.358873
1,3025432,t02,0.113627,546.0,0.164866,0.689208,0.134902,507.0,0.129094,1.04499,0.294489,968.0,0.160655,1.83305,0.370909,803.0,0.203555,1.82216,0.033478,379.0,0.156968,0.21328,0.195846,374.0,0.125601,1.55927,0.207391,2749.0,0.220258,0.941584,0.183793,2607.0,0.115641,1.58934,0.307434,596.0,0.171453,1.79311,0.307699,554.0,0.146212,2.10446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.176002,732.0,0.143585,1.22577,0.299369,1209.0,0.176313,1.69794,0.091169,1948.0,0.211858,0.430331,0.129214,1717.0,0.258094,0.500648,0.191039,1941.0,0.126531,1.50982,0.273202,2203.0,0.133034,2.05362,0.056021,463.0,0.096928,0.577969,0.138231,335.0,0.070097,1.972,0.312166,1018.0,0.181533,1.71961,0.153883,919.0,0.173025,0.889367,0.115799,907.0,0.126705,0.913927,0.347091,1114.0,0.148630,2.33527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.161390,1087.0,0.145512,1.10912,0.423286,810.0,0.192606,2.19768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.126571,2579.0,0.135973,0.93086,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.271734,2833.0,0.183231,1.48302,0.156398,2012.0,0.131630,1.18817,0.281738,1694.0,0.169455,1.66262,0.360782,1115.0,0.108716,3.31859,...,0.341538,0.408368,-0.043292,208.0,0.252956,-0.171145,-0.442349,1900.0,0.272994,-1.62036,-0.432820,2035.0,0.263355,-1.64349,-0.433669,887.0,0.282467,-1.53529,-0.475406,844.0,0.328365,-1.4478,0.296903,2995.0,0.616406,0.481668,1.024380,1755.0,0.875139,1.17053,-0.174242,1250.0,0.531172,-0.328032,0.273907,1247.0,0.566176,0.483784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.137021,1161.0,0.389855,-0.351468,-0.093878,700.0,0.191344,-0.490623,0.050562,2346.0,0.322168,0.156943,-0.107195,1231.0,0.379991,-0.282099,0.233504,2857.0,0.677051,0.344884,0.117943,2429.0,0.441671,0.267037,0.029994,2442.0,0.419484,0.071502,0.265862,2144.0,0.615516,0.431933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003355,359.0,0.325555,-0.010304,-0.211475,307.0,0.178446,-1.18509,0.041034,2111.0,0.341225,0.120254,-0.112228,2323.0,0.234674,-0.478231,-0.421614,1114.0,0.273757,-1.5401,-0.523767,1361.0,0.451818,-1.15924,-0.348391,116.0,0.242768,-1.43508,-0.155343,259.0,0.202486,-0.767178,0.209976,1389.0,0.348012,0.603358,0.421191,1239.0,0.590392,0.713409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.142289,686.0,0.290907,-0.489124,-0.068233,439.0,0.174616,-0.390758
2,3100205,t04,0.139939,867.0,0.165465,0.84573,0.037870,899.0,0.177122,0.213807,0.589120,1546.0,0.467161,1.26107,0.604697,1473.0,0.371502,1.62771,0.023225,860.0,0.262098,0.088613,0.024943,860.0,0.276152,0.090324,-0.039720,3024.0,0.517603,-0.076739,-0.071982,2973.0,0.611058,-0.117799,-0.092211,1393.0,0.295181,-0.312387,-0.288395,1313.0,0.271413,-1.06257,-0.226663,175.0,0.166302,-1.36296,-0.130247,185.0,0.077551,-1.6795,-0.018950,1120.0,0.422684,-0.044832,-0.148481,1506.0,0.377853,-0.392961,0.235594,2168.0,0.391305,0.602073,0.060858,1856.0,0.501290,0.121402,-0.366552,1918.0,0.430331,-0.85179,-0.352763,2172.0,0.446721,-0.789673,-0.250269,463.0,0.294207,-0.850655,-0.381167,312.0,0.278325,-1.36951,-0.052145,1425.0,0.297097,-0.175514,-0.079457,1390.0,0.384732,-0.206525,0.321510,918.0,0.317391,1.01298,0.064436,1298.0,0.285923,0.225362,0.431528,1346.0,0.253522,1.70213,0.085036,1380.0,0.309423,0.27482,0.587079,2152.0,0.326903,1.79588,0.043153,1827.0,0.365135,0.118185,0.449178,674.0,0.338122,1.32845,0.003613,843.0,0.370483,0.009751,0.163648,3974.0,0.389486,0.420165,0.383329,659.0,0.285332,1.34345,0.269155,723.0,0.426335,0.631323,0.020830,4627.0,0.448482,0.046444,0.056827,3137.0,0.438922,0.129469,-0.003930,2857.0,0.407966,-0.009633,-0.157291,2098.0,0.573083,-0.274466,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3123186,t02,0.452351,805.0,0.199426,2.26826,0.335390,903.0,0.145773,2.30078,0.569968,1205.0,0.343409,1.65973,0.534651,1221.0,0.347441,1.53883,0.469868,420.0,0.217331,2.16199,0.417174,634.0,0.175113,2.38232,0.585053,2662.0,0.576833,1.01425,0.583515,2735.0,0.463054,1.26014,0.119924,1400.0,0.327328,0.366372,0.050421,1313.0,0.214732,0.234809,0.367801,123.0,0.163352,2.25158,0.539917,187.0,0.263775,2.04688,0.289033,1081.0,0.694562,0.416138,0.473282,1501.0,0.590204,0.801896,1.195140,2114.0,1.034680,1.15508,0.750630,1772.0,0.735741,1.02024,0.192334,1941.0,0.295360,0.651184,0.160437,2203.0,0.220893,0.72631,0.429199,463.0,0.356899,1.20258,0.445741,335.0,0.325903,1.36771,0.527177,1471.0,0.493224,1.06884,0.429095,1368.0,0.498776,0.860297,0.505519,943.0,0.395888,1.27692,0.142778,1322.0,0.297458,0.479994,0.515149,1349.0,0.394942,1.30437,-0.088350,1445.0,0.266302,-0.331767,0.799870,2150.0,0.501012,1.59651,-0.005332,1786.0,0.366618,-0.014544,-0.200147,587.0,0.302685,-0.661238,-0.213778,814.0,0.384251,-0.556351,0.629517,3893.0,0.490847,1.28251,0.504211,664.0,0.415263,1.2142,-0.085074,932.0,0.396730,-0.214439,0.400830,4615.0,0.425784,0.941393,0.515955,3189.0,0.428555,1.20394,0.337457,2897.0,0.460327,0.733081,-0.083617,2097.0,0.418920,-0.199601,...,0.229704,-0.174704,-0.037178,1770.0,0.189296,-0.1964,0.405291,2088.0,0.700453,0.578612,0.148774,2276.0,0.568466,0.261711,0.758285,921.0,1.001440,0.757194,1.220150,878.0,0.855429,1.42636,0.640498,2711.0,0.579611,1.10505,0.573057,1410.0,0.429414,1.33451,0.214279,872.0,0.501358,0.427398,0.243620,921.0,0.349093,0.697865,0.003419,192.0,0.091503,0.03737,-0.052404,229.0,0.083628,-0.626634,-0.286001,727.0,0.136881,-2.08942,-0.207699,452.0,0.099877,-2.07955,-0.097337,1713.0,0.229068,-0.424925,-0.438290,849.0,0.283715,-1.54482,0.092599,2081.0,0.287442,0.322148,-0.057456,2072.0,0.269399,-0.213274,0.329504,2142.0,0.534527,0.616439,-0.087856,2026.0,0.304266,-0.288747,-0.059815,729.0,0.212534,-0.281436,-0.193080,687.0,0.145562,-1.32645,0.037931,962.0,0.169427,0.223878,-0.050627,1263.0,0.191912,-0.263801,0.354800,1882.0,0.581593,0.610049,-0.145488,2195.0,0.401424,-0.36243,-0.518090,1027.0,0.569785,-0.909273,-0.426494,1466.0,0.400121,-1.06591,-0.041899,2886.0,0.350476,-0.119549,-0.136949,3095.0,0.377484,-0.362794,-0.220354,4343.0,0.460515,-0.478495,-0.215387,3870.0,0.414186,-0.520024,-0.356431,316.0,0.273912,-1.30126,-0.208138,429.0,0.158657,-1.31187,-0.342574,879.0,0.422314,-0.811181,-0.289408,891.0,0.262304,-1.10333,-0.378041,2188.0,0.490212,-0.771178,-0.310544,2772.0,0.371033,-0.836973
4,3149469,t04,0.040562,893.0,0.120040,0.337906,0.057094,929.0,0.084127,0.678674,0.715635,1795.0,0.814607,0.878503,0.465257,1613.0,0.699639,0.664996,0.086729,598.0,0.127595,0.679721,0.061092,699.0,0.131129,0.46589,0.283188,3283.0,0.698636,0.405345,0.115254,3042.0,0.384171,0.300007,-0.058804,1400.0,0.267199,-0.220077,-0.089081,1313.0,0.217335,-0.409882,-0.065114,214.0,0.140305,-0.464085,0.003117,231.0,0.107680,0.028951,0.544136,1132.0,0.670309,0.811768,0.171061,1593.0,0.675009,0.25342,0.447225,2239.0,0.461555,0.968951,0.260119,1861.0,0.329534,0.789354,-0.111806,1941.0,0.262060,-0.426642,-0.092704,2203.0,0.236883,-0.39135,-0.092909,463.0,0.337664,-0.275151,-0.087965,333.0,0.245930,-0.357683,0.016409,1468.0,0.312351,0.052534,0.061149,1388.0,0.293336,0.20846,0.430153,951.0,0.490740,0.876541,0.030527,1333.0,0.264115,0.115584,0.342418,1536.0,0.425640,0.804478,0.002211,1425.0,0.172598,0.012808,0.505230,2281.0,0.396215,1.27514,0.090858,1833.0,0.243958,0.372434,-0.251688,655.0,0.189224,-1.33011,-0.171025,806.0,0.151825,-1.12646,0.295869,4359.0,0.558317,0.52993,0.154025,803.0,0.292999,0.525685,0.172828,936.0,0.171930,1.00523,0.067026,4737.0,0.284158,0.235876,0.236711,3275.0,0.473211,0.500223,0.020163,2876.0,0.459027,0.043926,-0.176451,2102.0,0.346868,-0.508697,...,0.176684,0.011733,-0.045650,1770.0,0.141578,-0.322437,0.158706,2090.0,0.463606,0.34233,0.142782,2294.0,0.506302,0.282009,0.968197,918.0,0.295598,3.27539,1.201910,933.0,0.425413,2.82528,0.633698,3094.0,0.531461,1.19237,0.748557,1837.0,0.491396,1.52333,0.231626,1227.0,0.518365,0.446841,0.344886,1261.0,0.350064,0.985208,0.037990,238.0,0.101460,0.374438,0.028736,232.0,0.083830,0.342791,0.021626,1060.0,0.156352,0.138318,-0.094237,632.0,0.155224,-0.607106,0.505662,2397.0,0.488377,1.03539,-0.021136,1278.0,0.289804,-0.07293,0.042351,3463.0,0.218239,0.194057,-0.041676,3157.0,0.178782,-0.233112,0.299409,3116.0,0.333196,0.898596,0.056400,2947.0,0.158052,0.356848,0.192774,580.0,0.166092,1.16065,0.149665,515.0,0.143127,1.04568,-0.140662,965.0,0.123149,-1.14221,-0.095585,1254.0,0.123786,-0.772176,0.359050,2084.0,0.432992,0.82923,0.123235,2309.0,0.251689,0.489633,-0.134938,1234.0,0.199143,-0.677594,-0.194304,1892.0,0.225261,-0.862569,0.239911,2519.0,0.342920,0.699613,0.319501,2858.0,0.511272,0.624913,-0.173232,4478.0,0.330058,-0.524853,-0.164424,4116.0,0.430160,-0.38224,0.142038,519.0,0.181949,0.780645,-0.043563,623.0,0.154002,-0.282874,0.050297,1055.0,0.221470,0.227106,-0.067017,1014.0,0.138757,-0.482976,-0.095730,2240.0,0.176305,-0.542981,-0.205495,2890.0,0.237867,-0.863908

In [28]:
# 3) Match motion + contrasts together (merge)
# Merge by ID and reconcile session columns from both sources.
id_col = "ID" if "ID" in motion_wide.columns else motion_wide.columns[0]

merged = motion_wide.merge(
    contrasts_wide,
    on=id_col,
    how="outer",
    suffixes=("_motion", "_contrasts"),
)

# Reconcile T1/T2 session labels if duplicated by merge
if "T1_motion" in merged.columns and "T1_contrasts" in merged.columns:
    merged["T1"] = merged["T1_motion"].combine_first(merged["T1_contrasts"])
    merged["T1_mismatch"] = (
        merged["T1_motion"].notna()
        & merged["T1_contrasts"].notna()
        & (merged["T1_motion"] != merged["T1_contrasts"])
    )

if "T2_motion" in merged.columns and "T2_contrasts" in merged.columns:
    merged["T2"] = merged["T2_motion"].combine_first(merged["T2_contrasts"])
    merged["T2_mismatch"] = (
        merged["T2_motion"].notna()
        & merged["T2_contrasts"].notna()
        & (merged["T2_motion"] != merged["T2_contrasts"])
    )

# Keep clean session columns first
drop_cols = [c for c in ["T1_motion", "T1_contrasts", "T2_motion", "T2_contrasts"] if c in merged.columns]
merged = merged.drop(columns=drop_cols)

front = [c for c in [id_col, "T1", "T2", "T1_mismatch", "T2_mismatch"] if c in merged.columns]
rest = [c for c in merged.columns if c not in front]
merged_wide = merged[front + rest]

print("Merged wide:", merged_wide.shape)
print("T1 mismatch count:", int(merged_wide.get("T1_mismatch", pd.Series(dtype=bool)).sum()))
print("T2 mismatch count:", int(merged_wide.get("T2_mismatch", pd.Series(dtype=bool)).sum()))
merged_wide.head()

Merged wide: (74, 687)
T1 mismatch count: 2
T2 mismatch count: 0

,ID,T1,T2,T1_mismatch,T2_mismatch,TD_mean_T1,TD_STD_T1,TD_median_T1,TD_max_T1,TD_>1mm_T1,TD_>2mm_T1,TD_>3mm_T1,STS_mean_T1,STS_STD_T1,STS_median_T1,STS_max_T1,STS_>0.5mm_T1,STS_>1mm_T1,TD_mean_T2,TD_STD_T2,TD_median_T2,TD_max_T2,TD_>1mm_T2,TD_>2mm_T2,TD_>3mm_T2,STS_mean_T2,STS_STD_T2,STS_median_T2,STS_max_T2,STS_>0.5mm_T2,STS_>1mm_T2,Hippocampus_L_Average_T1,Hippocampus_L_Size_T1,Hippocampus_L_Std.Dev._T1,Hippocampus_L_T_T1,Hippocampus_R_Average_T1,Hippocampus_R_Size_T1,Hippocampus_R_Std.Dev._T1,Hippocampus_R_T_T1,Parietal_Sup_L_Average_T1,Parietal_Sup_L_Size_T1,Parietal_Sup_L_Std.Dev._T1,Parietal_Sup_L_T_T1,Parietal_Sup_R_Average_T1,Parietal_Sup_R_Size_T1,Parietal_Sup_R_Std.Dev._T1,Parietal_Sup_R_T_T1,ParaHippocampal_L_Average_T1,ParaHippocampal_L_Size_T1,ParaHippocampal_L_Std.Dev._T1,ParaHippocampal_L_T_T1,ParaHippocampal_R_Average_T1,ParaHippocampal_R_Size_T1,ParaHippocampal_R_Std.Dev._T1,ParaHippocampal_R_T_T1,Precuneus_L_Average_T1,Precuneus_L_Size_T1,Precuneus_L_Std.Dev._T1,Precuneus_L_T_T1,Precuneus_R_Average_T1,Precuneus_R_Size_T1,Precuneus_R_Std.Dev._T1,Precuneus_R_T_T1,Cingulum_Ant_L_Average_T1,Cingulum_Ant_L_Size_T1,Cingulum_Ant_L_Std.Dev._T1,Cingulum_Ant_L_T_T1,Cingulum_Ant_R_Average_T1,Cingulum_Ant_R_Size_T1,Cingulum_Ant_R_Std.Dev._T1,Cingulum_Ant_R_T_T1,Amygdala_L_Average_T1,Amygdala_L_Size_T1,Amygdala_L_Std.Dev._T1,Amygdala_L_T_T1,Amygdala_R_Average_T1,Amygdala_R_Size_T1,Amygdala_R_Std.Dev._T1,Amygdala_R_T_T1,Angular_L_Average_T1,Angular_L_Size_T1,Angular_L_Std.Dev._T1,Angular_L_T_T1,Angular_R_Average_T1,Angular_R_Size_T1,Angular_R_Std.Dev._T1,Angular_R_T_T1,Calcarine_L_Average_T1,Calcarine_L_Size_T1,Calcarine_L_Std.Dev._T1,Calcarine_L_T_T1,Calcarine_R_Average_T1,Calcarine_R_Size_T1,Calcarine_R_Std.Dev._T1,Calcarine_R_T_T1,Cingulum_Mid_L_Average_T1,Cingulum_Mid_L_Size_T1,Cingulum_Mid_L_Std.Dev._T1,Cingulum_Mid_L_T_T1,Cingulum_Mid_R_Average_T1,Cingulum_Mid_R_Size_T1,Cingulum_Mid_R_Std.Dev._T1,Cingulum_Mid_R_T_T1,Cingulum_Post_L_Average_T1,Cingulum_Post_L_Size_T1,Cingulum_Post_L_Std.Dev._T1,Cingulum_Post_L_T_T1,Cingulum_Post_R_Average_T1,Cingulum_Post_R_Size_T1,Cingulum_Post_R_Std.Dev._T1,Cingulum_Post_R_T_T1,Cuneus_L_Average_T1,Cuneus_L_Size_T1,Cuneus_L_Std.Dev._T1,Cuneus_L_T_T1,Cuneus_R_Average_T1,Cuneus_R_Size_T1,Cuneus_R_Std.Dev._T1,Cuneus_R_T_T1,Frontal_Inf_Oper_L_Average_T1,Frontal_Inf_Oper_L_Size_T1,Frontal_Inf_Oper_L_Std.Dev._T1,Frontal_Inf_Oper_L_T_T1,Frontal_Inf_Oper_R_Average_T1,Frontal_Inf_Oper_R_Size_T1,Frontal_Inf_Oper_R_Std.Dev._T1,Frontal_Inf_Oper_R_T_T1,Frontal_Inf_Orb_L_Average_T1,Frontal_Inf_Orb_L_Size_T1,Frontal_Inf_Orb_L_Std.Dev._T1,Frontal_Inf_Orb_L_T_T1,Frontal_Inf_Orb_R_Average_T1,Frontal_Inf_Orb_R_Size_T1,Frontal_Inf_Orb_R_Std.Dev._T1,Frontal_Inf_Orb_R_T_T1,Frontal_Inf_Tri_L_Average_T1,Frontal_Inf_Tri_L_Size_T1,Frontal_Inf_Tri_L_Std.Dev._T1,Frontal_Inf_Tri_L_T_T1,Frontal_Inf_Tri_R_Average_T1,Frontal_Inf_Tri_R_Size_T1,Frontal_Inf_Tri_R_Std.Dev._T1,Frontal_Inf_Tri_R_T_T1,Frontal_Med_Orb_L_Average_T1,Frontal_Med_Orb_L_Size_T1,Frontal_Med_Orb_L_Std.Dev._T1,Frontal_Med_Orb_L_T_T1,Frontal_Med_Orb_R_Average_T1,Frontal_Med_Orb_R_Size_T1,Frontal_Med_Orb_R_Std.Dev._T1,...,Insula_L_Std.Dev._T2,Insula_L_T_T2,Insula_R_Average_T2,Insula_R_Size_T2,Insula_R_Std.Dev._T2,Insula_R_T_T2,Lingual_L_Average_T2,Lingual_L_Size_T2,Lingual_L_Std.Dev._T2,Lingual_L_T_T2,Lingual_R_Average_T2,Lingual_R_Size_T2,Lingual_R_Std.Dev._T2,Lingual_R_T_T2,Occipital_Inf_L_Average_T2,Occipital_Inf_L_Size_T2,Occipital_Inf_L_Std.Dev._T2,Occipital_Inf_L_T_T2,Occipital_Inf_R_Average_T2,Occipital_Inf_R_Size_T2,Occipital_Inf_R_Std.Dev._T2,Occipital_Inf_R_T_T2,Occipital_Mid_L_Average_T2,Occipital_Mid_L_Size_T2,Occipital_Mid_L_Std.Dev._T2,Occipital_Mid_L_T_T2,Occipital_Mid_R_Average_T2,Occipital_Mid_R_Size_T2,Occipital_Mid_R_Std.Dev._T2,Occipital_Mid_R_T_T2,Occipital_Sup_L_Average_T2,Occipital_Sup_L_Size_T2,Occipital_Sup_L_Std.Dev._T2,Occipital_Sup_L_T_T2,Occipital_Sup_R_Average_T2,Occipital_Sup_R_Size_T2,Occipital_Sup_R_Std.Dev._T2,Occipital_Sup_R_T_T2,Olfactory_L_Average_T2,Olfactory_L_Size_T2,Olfactory_L_Std.Dev._T2,Olfactory_L_T_T2,Olfactory_R_Average_T2,Olfactory_R_Size_T2,Olfactory_R_Std.Dev._T2,Olfactory_R_T_T2,Paracentral_Lobule_L_Average_T2,Paracentral_Lobule_L_Size_T2,Paracentral_Lobule_L_Std.Dev._T2,Paracentral_Lobule_L_T_T2,Paracentral_Lobule_R_Average_T2,Paracentral_Lobule_R_Size_T2,Paracentral_Lobule_R_Std.Dev._T2,Paracentral_Lobule_R_T_T2,Parietal_Inf_L_Average_T2,Parietal_Inf_L_Size_T2,Parietal_Inf_L_Std.Dev._T2,Parietal_Inf_L_T_T2,Parietal_Inf_R_Average_T2,Parietal_Inf_R_Size_T2,Parietal_Inf_R_Std.Dev._T2,Parietal_Inf_R_T_T2,Postcentral_L_Average_T2,Postcentral_L_Size_T2,Postcentral_L_Std.Dev._T2,Postcentral_L_T_T2,Postcentral_R_Average_T2,Postcentral_R_Size_T2,Postcentral_R_Std.Dev._T2,Postcentral_R_T_T2,Precentral_L_Average_T2,Precentral_L_Size_T2,Precentral_L_Std.Dev._T2,Precentral_L_T_T2,Precentral_R_Average_T2,Precentral_R_Size_T2,Precentral_R_Std.Dev._T2,Precentral_R_T_T2,Rectus_L_Average_T2,Rectus_L_Size_T2,Rectus_L_Std.Dev._T2,Rectus_L_T_T2,Rectus_R_Average_T2,Rectus_R_Size_T2,Rectus_R_Std.Dev._T2,Rectus_R_T_T2,Rolandic_Oper_L_Average_T2,Rolandic_Oper_L_Size_T2,Rolandic_Oper_L_Std.Dev._T2,Rolandic_Oper_L_T_T2,Rolandic_Oper_R_Average_T2,Rolandic_Oper_R_Size_T2,Rolandic_Oper_R_Std.Dev._T2,Rolandic_Oper_R_T_T2,Supp_Motor_Area_L_Average_T2,Supp_Motor_Area_L_Size_T2,Supp_Motor_Area_L_Std.Dev._T2,Supp_Motor_Area_L_T_T2,Supp_Motor_Area_R_Average_T2,Supp_Motor_Area_R_Size_T2,Supp_Motor_Area_R_Std.Dev._T2,Supp_Motor_Area_R_T_T2,SupraMarginal_L_Average_T2,SupraMarginal_L_Size_T2,SupraMarginal_L_Std.Dev._T2,SupraMarginal_L_T_T2,SupraMarginal_R_Average_T2,SupraMarginal_R_Size_T2,SupraMarginal_R_Std.Dev._T2,SupraMarginal_R_T_T2,Temporal_Inf_L_Average_T2,Temporal_Inf_L_Size_T2,Temporal_Inf_L_Std.Dev._T2,Temporal_Inf_L_T_T2,Temporal_Inf_R_Average_T2,Temporal_Inf_R_Size_T2,Temporal_Inf_R_Std.Dev._T2,Temporal_Inf_R_T_T2,Temporal_Mid_L_Average_T2,Temporal_Mid_L_Size_T2,Temporal_Mid_L_Std.Dev._T2,Temporal_Mid_L_T_T2,Temporal_Mid_R_Average_T2,Temporal_Mid_R_Size_T2,Temporal_Mid_R_Std.Dev._T2,Temporal_Mid_R_T_T2,Temporal_Pole_Mid_L_Average_T2,Temporal_Pole_Mid_L_Size_T2,Temporal_Pole_Mid_L_Std.Dev._T2,Temporal_Pole_Mid_L_T_T2,Temporal_Pole_Mid_R_Average_T2,Temporal_Pole_Mid_R_Size_T2,Temporal_Pole_Mid_R_Std.Dev._T2,Temporal_Pole_Mid_R_T_T2,Temporal_Pole_Sup_L_Average_T2,Temporal_Pole_Sup_L_Size_T2,Temporal_Pole_Sup_L_Std.Dev._T2,Temporal_Pole_Sup_L_T_T2,Temporal_Pole_Sup_R_Average_T2,Temporal_Pole_Sup_R_Size_T2,Temporal_Pole_Sup_R_Std.Dev._T2,Temporal_Pole_Sup_R_T_T2,Temporal_Sup_L_Average_T2,Temporal_Sup_L_Size_T2,Temporal_Sup_L_Std.Dev._T2,Temporal_Sup_L_T_T2,Temporal_Sup_R_Average_T2,Temporal_Sup_R_Size_T2,Temporal_Sup_R_Std.Dev._T2,Temporal_Sup_R_T_T2
0,3002498,t04,t06,False,False,0.4579,0.1482,0.4989,0.7831,0.0,0.0,0.0,0.1565,0.1132,0.1324,1.1124,4.0,1.0,0.2214,0.0826,0.2172,0.4921,0.0,0.0,0.0,0.1950,0.1154,0.1727,1.2546,6.0,1.0,0.204866,932.0,0.187010,1.09548,0.141722,946.0,0.193112,0.733888,-0.050055,1780.0,0.240597,-0.208046,-0.366434,1643.0,0.337222,-1.08663,0.035731,823.0,0.184553,0.193611,0.014009,957.0,0.165820,0.084486,-0.097804,3425.0,0.258852,-0.377836,-0.249717,3089.0,0.311789,-0.800918,-0.064639,1394.0,0.299906,-0.21553,-0.086699,1311.0,0.240799,-0.36005,-0.095064,220.0,0.260898,-0.364373,-0.060107,248.0,0.098262,-0.611702,-0.365052,1081.0,0.298737,-1.22199,-0.487776,1471.0,0.447072,-1.09105,0.259278,2195.0,0.359261,0.721698,0.170228,1857.0,0.400255,0.425298,0.160467,1935.0,0.210446,0.762511,0.102210,2203.0,0.193602,0.527941,0.210002,463.0,0.244451,0.859076,-0.010481,335.0,0.167743,-0.062482,0.085524,1451.0,0.356379,0.239981,-0.049829,1414.0,0.296499,-0.168059,0.117714,911.0,0.212472,0.554023,0.049217,1252.0,0.332238,0.148139,-0.197369,1515.0,0.293561,-0.672327,-0.307062,1398.0,0.258120,-1.18961,-0.093633,2142.0,0.341122,-0.274484,-0.085812,1717.0,0.253189,-0.338926,0.012690,698.0,0.219897,0.057711,-0.331844,847.0,0.287823,...,0.542574,0.378826,-0.050817,1770.0,0.653383,-0.077775,0.234619,2089.0,0.475664,0.493245,0.240846,2278.0,0.619264,0.388924,1.013770,906.0,0.423499,2.3938,1.144590,868.0,0.410760,2.78652,0.643511,3024.0,0.451096,1.42655,0.692905,1750.0,0.413835,1.67435,0.725632,1262.0,0.408545,1.77614,0.388638,1285.0,0.282067,1.37782,0.453129,192.0,0.352038,1.28716,0.157663,199.0,0.173972,0.906255,0.337478,1297.0,0.258753,1.30425,0.377556,779.0,0.347475,1.08657,0.989604,2343.0,0.380336,2.60192,0.079665,1166.0,0.484766,0.164336,0.612459,3467.0,0.369901,1.65574,0.684637,3273.0,0.373265,1.83418,0.661695,3129.0,0.278573,2.3753,0.692507,3016.0,0.310242,2.23215,0.423050,622.0,0.316394,1.3371,0.301388,568.0,0.245449,1.22791,-0.148442,947.0,0.210814,-0.704137,-0.071791,1246.0,0.367237,-0.19549,0.679373,2124.0,0.305418,2.22441,0.568340,2367.0,0.324584,1.75098,0.542410,1173.0,0.458321,1.18347,0.396334,1715.0,0.430618,0.920384,0.412739,2391.0,0.404667,1.01995,0.309216,2997.0,0.376993,0.820215,-0.037256,4197.0,0.436231,-0.085405,-0.129824,3792.0,0.556996,-0.233078,0.121128,459.0,0.326445,0.371052,0.366434,634.0,0.323095,1.13414,0.573804,985.0,0.758305,0.756692,0.775702,900.0,0.781886,0.99209,-0.244715,2174.0,0.658876,-0.371413,-0.198090,2813.0,0.551978,-0.358873
1,3025432,t02,t06,False,False,0.8227,0.3557,0.9174,1.4089,284.0,0.0,0.0,0.2220,0.2880,0.1585,2.8437,29.0,15.0,0.8135,0.2308,0.8608,1.5575,112.0,0.0,0.0,0.1848,0.2564,0.1360,2.9957,17.0,11.0,0.113627,546.0,0.164866,0.689208,0.134902,507.0,0.129094,1.04499,0.294489,968.0,0.160655,1.83305,0.370909,803.0,0.203555,1.82216,0.033478,379.0,0.156968,0.21328,0.195846,374.0,0.125601,1.55927,0.207391,2749.0,0.220258,0.941584,0.183793,2607.0,0.115641,1.58934,0.307434,596.0,0.171453,1.79311,0.307699,554.0,0.146212,2.10446,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.176002,732.0,0.143585,1.22577,0.299369,1209.0,0.176313,1.69794,0.091169,1948.0,0.211858,0.430331,0.129214,1717.0,0.258094,0.500648,0.191039,1941.0,0.126531,1.50982,0.273202,2203.0,0.133034,2.05362,0.056021,463.0,0.096928,0.577969,0.138231,335.0,0.070097,1.972,0.312166,1018.0,0.181533,1.71961,0.153883,919.0,0.173025,0.889367,0.115799,907.0,0.126705,0.913927,0.347091,1114.0,0.148630,2.33527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.161390,1087.0,0.145512,1.10912,0.423286,810.0,0.192606,2.19768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,0.341538,0.408368,-0.043292,208.0,0.252956,-0.171145,-0.442349,1900.0,0.272994,-1.62036,-0.432820,2035.0,0.263355,-1.64349,-0.433669,887.0,0.282467,-1.53529,-0.475406,844.0,0.328365,-1.4478,0.296903,2995.0,0.616406,0.481668,1.024380,1755.0,0.875139,1.17053,-0.174242,1250.0,0.531172,-0.328032,0.273907,1247.0,0.566176,0.483784,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.137021,1161.0,0.389855,-0.351468,-0.093878,700.0,0.191344,-0.490623,0.050562,2346.0,0.322168,0.156943,-0.107195,1231.0,0.379991,-0.282099,0.233504,2857.0,0.677051,0.344884,0.117943,2429.0,0.441671,0.267037,0.029994,2442.0,0.419484,0.071502,0.265862,2144.0,0.615516,0.431933,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.003355,359.0,0.325555,-0.010304,-0.211475,307.0,0.178446,-1.18509,0.041034,2111.0,0.341225,0.120254,-0.112228,2323.0,0.234674,-0.478231,-0.421614,1114.0,0.273757,-1.5401,-0.523767,1361.0,0.451818,-1.15924,-0.348391,116.0,0.242768,-1.43508,-0.155343,259.0,0.202486,-0.767178,0.209976,1389.0,0.348012,0.603358,0.421191,1239.0,0.590392,0.713409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-0.142289,686.0,0.290907,-0.489124,-0.068233,439.0,0.174616,-0.390758
2,3100205,t04,t08,False,False,0.9387,0.2679,1.0113,1.3353,320.0,0.0,0.0,0.2841,0.1428,0.2588,2.6461,23.0,1.0,0.6674,0.1899,0.6966,1.1379,16.0,0.0,0.0,0.3701,0.1898,0.3464,2.6835,127.0,6.0,0.139939,867.0,0.165465,0.84573,0.037870,899.0,0.177122,0.213807,0.589120,1546.0,0.467161,1.26107,0.604697,1473.0,0.371502,1.62771,0.023225,860.0,0.262098,0.088613,0.024943,860.0,0.276152,0.090324,-0.039720,3024.0,0.517603,-0.076739,-0.071982,2973.0,0.611058,-0.117799,-0.092211,1393.0,0.295181,-0.312387,-0.288395,1313.0,0.271413,-1.06257,-0.226663,175.0,0.166302,-1.36296,-0.130247,185.0,0.077551,-1.6795,-0.018950,1120.0,0.422684,-0.044832,-0.148481,1506.0,0.377853,-0.392961,0.235594,2168.0,0.391305,0.602073,0.060858,1856.0,0.501290,0.121402,-0.366552,1918.0,0.430331,-0.85179,-0.352763,2172.0,0.446721,-0.789673,-0.250269,463.0,0.294207,-0.850655,-0.381167,312.0,0.278325,-1.36951,-0.052145,1425.0,0.297097,-0.175514,-0.079457,1390.0,0.384732,-0.206525,0.321510,918.0,0.317391,1.01298,0.064436,1298.0,0.285923,0.225362,0.431528,1346.0,0.253522,1.70213,0.085036,1380.0,0.309423,0.27482,0.587079,2152.0,0.326903,1.79588,0.043153,1827.0,0.365135,0.118185,0.449178,674.0,0.338122,1.32845,0.003613,843.0,0.370483,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3123186,t02,t04,False,False,0.5541,0.2232,0.6061,1.0273,6.0,0.0,0.0,0.1965,0.1636,0.1386,1.6715,37.0,1.0,0.1691,0.0976,0.1458,0.5049,0.0,0.0,0.0,0.2641,0.2057,0.1803,1.0529,54.0,1.0,0.452351,805.0,0.199426,2.26826,0.335390,903.0,0.145773,2.30078,0.569968,1205.0,0.343409,1.65973,0.534651,1221.0,0.347441,1.53883,0.469868,420.0,0.217331,2.16199,0.417174,634.0,0.175113,2.38232,0.585053,2662.0,0.576833,1.01425,0.583515,2735.0,0.463054,1.26014,0.119924,1400.0,0.327328,0.366372,0.050421,1313.0,0.214732,0.234809,0.367801,123.0,0.163352,2.25158,0.539917,187.0,0.263775,2.04688,0.289033,1081.0,0.694562,0.416138,0.473282,1501.0,0.590204,0.801896,1.195140,2114.0,1.034680,1.15508,0.750630,1772.0,0.735741,1.02024,0.192334,1941.0,0.295360,0.651184,0.160437,2203.0,0.220893,0.72631,0.429199,463.0,0.356899,1.20258,0.445741,335.0,0.325903,1.36771,0.527177,1471.0,0.493224,1.06884,0.429095,1368.0,0.498776,0.860297,0.505519,943.0,0.395888,1.27692,0.142778,1322.0,0.297458,0.479994,0.515149,1349.0,0.394942,1.30437,-0.088350,1445.0,0.266302,-0.331767,0.799870,2150.0,0.501012,1.59651,-0.005332,1786.0,0.366618,-0.014544,-0.200147,587.0,0.302685,-0.661238,-0.213778,814.0,0.384251,...,0.229704,-0.174704,-0.037178,1770.0,0.189296,-0.1964,0.405291,2088.0,0.700453,0.578612,0.148774,2276.0,0.568466,0.261711,0.758285,921.0,1.001440,0.757194,1.220150,878.0,0.855429,1.42636,0.640498,2711.0,0.579611,1.10505,0.573057,1410.0,0.429414,1.33451,0.214279,872.0,0.501358,0.427398,0.243620,921.0,0.349093,0.697865,0.003419,192.0,0.091503,0.03737,-0.052404,229.0,0.083628,-0.626634,-0.286001,727.0,0.136881,-2.08942,-0.207699,452.0,0.099877,-2.07955,-0.097337,1713.0,0.229068,-0.424925,-0.438290,849.0,0.283715,-1.54482,0.092599,2081.0,0.287442,0.322148,-0.057456,2072.0,0.269399,-0.213274,0.329504,2142.0,0.534527,0.616439,-0.087856,2026.0,0.304266,-0.288747,-0.059815,729.0,0.212534,-0.281436,-0.193080,687.0,0.145562,-1.32645,0.037931,962.0,0.169427,0.223878,-0.050627,1263.0,0.191912,-0.263801,0.354800,1882.0,0.581593,0.610049,-0.145488,2195.0,0.401424,-0.36243,-0.518090,1027.0,0.569785,-0.909273,-0.426494,1466.0,0.400121,-1.06591,-0.041899,2886.0,0.350476,-0.119549,-0.136949,3095.0,0.377484,-0.362794,-0.220354,4343.0,0.460515,-0.478495,-0.215387,3870.0,0.414186,-0.520024,-0.356431,316.0,0.273912,-1.30126,-0.208138,429.0,0.158657,-1.31187,-0.342574,879.0,0.422314,-0.811181,-0.289408,891.0,0.262304,-1.10333,-0.378041,2188.0,0.490212,-0.771178,-0.310544,2772.0,0.371033,-0.836973
4,3149469,t04,t06,False,False,0.3443,0.1434,0.3848,0.6536,0.0,0.0,0.0,0.1342,0.0493,0.1312,0.3103,0.0,0.0,0.4423,0.2374,0.4952,0.9153,0.0,0.0,0.0,0.1949,0.0819,0.1873,0.7871,4.0,0.0,0.040562,893.0,0.120040,0.337906,0.057094,929.0,0.084127,0.678674,0.715635,1795.0,0.814607,0.878503,0.465257,1613.0,0.699639,0.664996,0.086729,598.0,0.127595,0.679721,0.061092,699.0,0.131129,0.46589,0.283188,3283.0,0.698636,0.405345,0.115254,3042.0,0.384171,0.300007,-0.058804,1400.0,0.267199,-0.220077,-0.089081,1313.0,0.217335,-0.409882,-0.065114,214.0,0.140305,-0.464085,0.003117,231.0,0.107680,0.028951,0.544136,1132.0,0.670309,0.811768,0.171061,1593.0,0.675009,0.25342,0.447225,2239.0,0.461555,0.968951,0.260119,1861.0,0.329534,0.789354,-0.111806,1941.0,0.262060,-0.426642,-0.092704,2203.0,0.236883,-0.39135,-0.092909,463.0,0.337664,-0.275151,-0.087965,333.0,0.245930,-0.357683,0.016409,1468.0,0.312351,0.052534,0.061149,1388.0,0.293336,0.20846,0.430153,951.0,0.490740,0.876541,0.030527,1333.0,0.264115,0.115584,0.342418,1536.0,0.425640,0.804478,0.002211,1425.0,0.172598,0.012808,0.505230,2281.0,0.396215,1.27514,0.090858,1833.0,0.243958,0.372434,-0.251688,655.0,0.189224,-1.33011,-0.171025,806.0,0.151825,...,0.176684,0.011733,-0.045650,1770.0,0.141578,-0.322437,0.158706,2090.0,0.463606,0.34233,0.142782,2294.0,0.506302,0.282009,0.968197,918.0,0.295598,3.27539,1.201910,933.0,0.425413,2.82528,0.633698,3094.0,0.531461,1.19237,0.748557,1837.0,0.491396,1.52333,0.231626,1227.0,0.518365,0.446841,0.344886,1261.0,0.350064,0.985208,0.037990,238.0,0.101460,0.374438,0.028736,232.0,0.083830,0.342791,0.021626,1060.0,0.156352,0.138318,-0.094237,632.0,0.155224,-0.607106,0.505662,2397.0,0.488377,1.03539,-0.021136,1278.0,0.289804,-0.07293,0.042351,3463.0,0.218239,0.194057,-0.041676,3157.0,0.178782,-0.233112,0.299409,3116.0,0.333196,0.898596,0.056400,2947.0,0.158052,0.356848,0.192774,580.0,0.166092,1.16065,0.149665,515.0,0.143127,1.04568,-0.140662,965.0,0.123149,-1.14221,-0.095585,1254.0,0.123786,-0.772176,0.359050,2084.0,0.432992,0.82923,0.123235,2309.0,0.251689,0.489633,-0.134938,1234.0,0.199143,-0.677594,-0.194304,1892.0,0.225261,-0.862569,0.239911,2519.0,0.342920,0.699613,0.319501,2858.0,0.511272,0.624913,-0.173232,4478.0,0.330058,-0.524853,-0.164424,4116.0,0.430160,-0.38224,0.142038,519.0,0.181949,0.780645,-0.043563,623.0,0.154002,-0.282874,0.050297,1055.0,0.221470,0.227106,-0.067017,1014.0,0.138757,-0.482976,-0.095730,2240.0,0.176305,-0.542981,-0.205495,2890.0,0.237867,-0.863908

In [29]:
# 4) Export all outputs
with pd.ExcelWriter(OUT_FILE, engine="openpyxl") as writer:
    motion_wide.to_excel(writer, sheet_name="ALL_MOTION_WIDE", index=False)
    contrasts_wide.to_excel(writer, sheet_name="CONTRASTS_WIDE", index=False)
    merged_wide.to_excel(writer, sheet_name="MERGED_WIDE", index=False)

print(f"Saved workbook: {OUT_FILE}")

Saved workbook: C:\Users\okkam\Desktop\labo\article 2\Longitudinal_Multimodal_Data_CIMAQ\fMRI\long_to_wide_fMRI_outputs.xlsx